# Generated by Django 6.1.1 on 2026-09-27 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.localdate)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.emprunteur')),
            ],
        ),
        migrations.CreateModel(
            name='FicheAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biographie', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('auteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('titre', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_pages', models.IntegerField()),
                ('resume', models.TextField(blank=True)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('it', 'Italien')], default='fr', max_length=2)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.auteur')),
                ('emprunteurs', models.ManyToManyField(blank=True, through='bibliotheque.Emprunt', to='membres.emprunteur')),
                ('genres', models.ManyToManyField(blank=True, to='bibliotheque.genre')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.livre'),
        ),
    ]
